### ISSUE TITLE
Button Overlap

### ISSUE THREAD

**Issue by MuttMeat** [nirewen/Discordify#5]
![discord_2018-12-13_15-40-12](https://user-images.githubusercontent.com/45852667/49945720-c32cd680-feed-11e8-803f-491a820bb06c.png)

**Comment by MasicoreLord** [comment]
Can't seem to reproduce this particular bug, I did see something like it before w/ that theme.  Fully restart your client, as it might be an outdated cache of the theme.

**Comment by MasicoreLord** [comment]
Closing, as it seems to be a non issue now.
